<div data-mage-init='{
    "collapsible":{
        "collapsible": true,
        "openedState": "active",
        "active": true,
        "saveState": true
    }}'>
    <div data-role="title">
        <h4>Fruit</h4>
    </div>
    <div data-role="content">
        <ul>
            <li>Orange</li>
            <li>Apple</li>
            <li>Banana</li>
        </ul>
    </div>
</div>

<div data-mage-init='{
    "collapsible":{
        "animate": { "duration": 1000, "easing": "easeOutCubic" }
    }}'>
    <div data-role="title">
        <h4>Exams</h4>
    </div>
    <div data-role="content">
        <ul>
            <li>Maths</li>
            <li>English</li>
            <li>Science</li>
        </ul>
    </div>
</div>

<!--COLLAPSIBLE WITH AJAX-->

<div data-mage-init='{
    "collapsible":{
        "animate": { "duration": 1000, "easing": "easeOutCubic" }
    }}'>
    <div class="collapsible__title" data-role="title">
        <h4>trigger</h4>
    </div>
    <div data-role="content">
        <ul>
            <li>loading</li>
        </ul>
    </div>
</div>
