<?php
$itemsData = $block->getData('noties_data');
?>

<ol>
    <?php foreach ($itemsData as $key => $item): ?>
        <?php if (is_array($item)): ?>
            <li><?= $block->escapeHtml(__($key)) ?>
                <ul>
                    <?php foreach ($item as $subItem): ?>
                        <li>
                            <?= $block->escapeHtml(__($subItem)) ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        <?php else: ?>
            <li><?= $block->escapeHtml(__($item)) ?></li>
        <?php endif; ?>
    <?php endforeach; ?>
</ol>
