<div data-bind="scope: 'custom1'">
    <!--        ko template: getTemplate() --><!--    /ko-->
</div>
<div data-bind="scope: 'custom2'">
    <!--        ko template: getTemplate() --><!--    /ko-->
</div>



<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "custom1": {
                        "component": "Magento_Theme/js/view/ui-import-export1",
                        "deps": ["custom2"]
                    },
                    "custom2": {
                        "component": "Magento_Theme/js/view/ui-import-export2"
                    }
                }
            }
        }
    }
</script>
