<div data-bind="scope:'ui-literals' ">
    <!--    ko template: getTemplate()-->
    <!--    /ko-->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "ui-literals": {
                        "component": "Magento_Theme/js/view/ui-literals"
                    }
                }
            }
        }
    }
</script>
