<div data-bind="scope:'ui-statefull' ">
    <!--    ko template: getTemplate()-->
    <!--    /ko-->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "ui-statefull": {
                        "component": "Magento_Theme/js/view/ui-statefull"
                    }
                }
            }
        }
    }
</script>
